### ISSUE TITLE
Mark a prerelease as such in Github.

### ISSUE THREAD

**Issue by scottux** [geddski/grunt-release#104]
There is a param when creating the github release, `prerelease: boolean` that will mark a release in github as being a pre-release.

The request object should look like:
```
{
    "tag_name": tagName,
    "name": tagMessage,
    "prerelease": type === 'prerelease'
}
```

**Comment by drublic** [comment]
This is a good idea. We should land this. Can you please open a Pull Request? That would be fantastic :)

**Comment by drublic** [comment]
Thanks for the work. Closing this in favor of #106.
