### ISSUE TITLE
CHANGELOG.md location

### ISSUE THREAD

**Issue by andre-ferreira-qlik** [geddski/grunt-release#111]
Is it possible to specify the location of CHANGELOG.md ?
I currently run my grunt task from a different location than the CHANGELOG and the release will fail because of it. I can set changelog to false, but its not ideal.

**Comment by drublic** [comment]
Please see the docs in the commit message: https://github.com/geddski/grunt-release/commit/9ffe8d3fde8c1d237635caa66fc3a0daea78c9fa

> `changelog` - you can set it to `true` to add a message in
  CHANGELOG.md or you can provide a string with a file name;
  default: `false`

**Comment by drublic** [comment]
PS: "file name" can also be a path with a file name.

**Comment by andre-ferreira-qlik** [comment]
Thanks!
