### ISSUE TITLE
Release to private repository failed with warning.

### ISSUE THREAD

**Issue by sreejasuma** [geddski/grunt-release#114]
In function githubRelease(), the post request, 
.post('https://api.github.com/repos/' + options.github.repo + '/releases') seems to be not valid for private repositories. And also '.set('Accept', 'application/vnd.github.manifold-preview')' is always throwing 406 error.
It would have been good to give the user the option to give the repo url and Accept in options  .
  github: {
		repo: 'https://github.XXXX.com/XXX/XXX', //put your user/repo here
		usernameVar: 'GITUSERNAME', //ENVIRONMENT VARIABLE that contains Github username
		passwordVar: 'GITPWD'
	    }

Eventhough its failing, actual release is happening in the github. But when tried to integrate with Jenkins, this will become a problem because of the build failure.

**Comment by drublic** [comment]
You can set an url via `github.apiRoot` now. This just landed in 2fccbc6d7a05659090e1e02a57615b71b97df25d. Please check it out.
If there is anything else that is missing and you still get errors, please open a new issue.

Thank you for taking the time to report this!
