### ISSUE TITLE
The tasks in beforeRelease and beforeBump actually run after the release was done

### ISSUE THREAD

**Issue by sorin7486** [geddski/grunt-release#118]
I added a build task in beforeRelease but it doesn't actually run before the release is done. Here's the output:

    Running "release:0.0.99" (release) task
    >> running beforeRelease
    >> bumped version of bower.json to 0.0.99
    >> staged bower.json
    >> Committed all files
    >> created new git tag: 0.0.99
    >> pushed to remote
    >> pushed new tag 0.0.99 to remote
    >> created 0.0.99 release on github.

    Running "clean:dist" (clean) task
    Cleaning dist/images...OK
    Cleaning dist/scripts...OK
    Cleaning dist/styles...OK
    Cleaning dist/views...OK
    ....

**Comment by bkingery** [comment]
+1

**Comment by jalet** [comment]
:+1:

**Comment by pascalgagneur** [comment]
:+1:

**Comment by chrisprice** [comment]
According to the [docs](http://gruntjs.com/api/grunt.task#grunt.task.run) tasks passed to the `grunt.task.run` call "will be run immediately after the current task completes". My workaround is to register a new task which calls my build task before the release task.

:+1:

**Comment by btilford** [comment]
That workaround won't work for my project. We have items in the build that reference the version so we need

1. Version bump
2. Build the project
3. Commit / tag / push

I tried using targets but grunt-release only works with the `[major,minor,patch,prerelease]` targets as far as I can tell.

**Comment by juliangarritano** [comment]
:+1:

**Comment by jpjoyal** [comment]
+1

**Comment by atti187** [comment]
@chrisprice The problem is that the "current task" is "release" and the beforeRelease-tasks are being run after release (which is too late).

**Comment by didlich** [comment]
+1

**Comment by drublic** [comment]
Thank you for the work. I've merged it new. There will be a new version with more fixes and stuff.
