### ISSUE TITLE
Allow uploading of asset(s) to GitHub release

### ISSUE THREAD

**Issue by gethinwebster** [geddski/grunt-release#134]
It would be great to support the uploading of one or more assets to the GitHub release as part of the release process:

https://developer.github.com/v3/repos/releases/#upload-a-release-asset

If there are no objections to this I'll attempt to put in a PR for this at some point, although if anyone else fancies tackling it in the meantime feel free!

**Comment by FagnerMartinsBrack** [comment]
Duplicated of #47

**Comment by drublic** [comment]
Thanks for the report. As @FagnerMartinsBrack said, please follow the discussion in the earlier bug #47.
