### ISSUE TITLE
commitMessage showing the version before the bump

### ISSUE THREAD

**Issue by tammorelli** [geddski/grunt-release#136]
My version in commitMessage: 'check out my release <%= version %>' is showing the version before being bumped, the other messages and tag creation are working properly.

**Comment by drublic** [comment]
Thanks for reporting. Will investigate and fix this bug with the next version.

**Comment by bago** [comment]
It works fine here with 0.13.1: which version are you using? What is the configuration?

**Comment by tammorelli** [comment]
Oh my, I don't even remember in what project this happened, if it doen't happen anymore I am closing it.
