### ISSUE TITLE
Changelog md not being updated with commits

### ISSUE THREAD

**Issue by angelblade27** [geddski/grunt-release#142]
When I run ```grunt release``` I see the changelog being updated however none of my commits are shown in the changelog. I'm using commitizen to commit my messages. The only thing I see updated in my changelog is the version number. Is it possible to pass a command to run for the changelog generation? Previously I was using cz-conventional-changelog

**Comment by deostroll** [comment]
Even I sort of ran into the same issue. What did you do?

**Comment by angelblade27** [comment]
If i remember correctly I wasn't tagging the build's properly

**Comment by deostroll** [comment]
My observation is that post grunt release command the changelog.md file
updates, but its not committed with the release... And that file remains in
a modified status post the operation...
