### ISSUE TITLE
Dead Project

### ISSUE THREAD

**Issue by dorgan** [geddski/grunt-release#150]
Is this project dead??

**Comment by dorgan** [comment]
If it is I would be more than willing to take it over.

**Comment by drublic** [comment]
@dorgan Sadly, kind of yes. Would be nice to get some contributions. Any suggestions on how to proceed on your end?

**Comment by dorgan** [comment]
IF you want to add me as an admin I am more than happy to tag another
release, since the last release is actually broken.

**Comment by dorgan** [comment]
So any thought on adding me as an admin??

**Comment by geddski** [comment]
I woukdnt call it dead at all. I use it all the time and so do others. It had over 26,000 downloads in the last month. 

It does need some updates & love though. @drublic has done an amazing job keeping it going. I'm ok with adding another admin if he is.

**Comment by dorgan** [comment]
good to hear, let me know.  I definitely use it on all my projects.

**Comment by drublic** [comment]
I would love to see you as an admin. @geddski Can you please do so? I am not able to do it.

(Sorry for the lack of updates.)

**Comment by geddski** [comment]
Yep will do

**Comment by hildjj** [comment]
Did you guys add @dorgan as an admin?  I would really like a new release to be cut to support Grunt1.

**Comment by geddski** [comment]
added on github. @dorgan what's your npm username so I can give you publish permissions?

**Comment by dorgan** [comment]
same username on npm

**Comment by geddski** [comment]
k you're set! Thanks for helping out!
