### ISSUE TITLE
Focus on the git part?

### ISSUE THREAD

**Issue by mar10** [geddski/grunt-release#24]
Just a thought, inspired by the discussion on #21 (and #7 ): maybe this module tries to accomplish too much? 
I am quite new to this node/grunt framework, but if I understand correctly, bumping, adjusting the source, and finally committing are all (potentially) complex in itself.

If this plugin does only one thing really good - tagging and committing - it can be easily used as one plugin in a custom grunt task.

Some ideas:
- default `bump: false` (or even remove this option)
- default `npm: false` (not used for query-plugins, for example)
- read version number from a canonical place (default: package.json)
- rename to 'grunt-git-release' or s.th.

**Comment by drublic** [comment]
Closing this now as there is no more information here. Thanks everyone.
