### ISSUE TITLE
Allow callbacks and command line parameter to create tag names

### ISSUE THREAD

**Issue by eskimoblood** [geddski/grunt-release#27]
I have the  following use case. From time to time I have to deploy a branch on a test stage. As this just a branch in development, I dont want bump the version number, but I have to create a new tag and update a CMakefile with a release number. It would be good if the `tagName` option could be a function and not just a string with place holders. This function, in my case,  could read the actual branch name and could then create  a branch name like 0.1.2-mybranch-1. The `1` would be passed in as command line parameter. And is also used to update my CMakefile, using the changes I"ve made in this pull request: https://github.com/geddski/grunt-release/pull/25

**Comment by drublic** [comment]
Closing this as there is not any work done on that. I don't see a lot of value here tbh.
