### ISSUE TITLE
Add ability to bump prerelease version after release

### ISSUE THREAD

**Issue by blalor** [geddski/grunt-release#50]
For CI purposes, it'd be nice to have the release tasks do an additional commit that bumps the version to something like `-alpha.0` or `-1`.  So move the version in `package.json` from `0.1.0` (`release`) → `0.1.1` (commit, tag, push, publish) → `0.1.2-1`.  This assumes that a subsequent run of `release` would recognize `0.1.2-1` and properly release `0.1.2`.

**Comment by drublic** [comment]
Please see #74 for further information. We should use this issue for all other work. Thanks for reporting.
