### ISSUE TITLE
Rename Tasks not possible

### ISSUE THREAD

**Issue by dodophoenix** [geddski/grunt-release#84]
The grunt-release plugin registers `release`  as a Task.
The release task of the grunt-release plugin conflicts with an existing release task in ourt project. Our existing 'relase' task is part of a complex build process. So renaming our 'release' task would not be a solution here. To avoid such problems grunt allows to rename tasks using 
grunt.renameTask('release','grunt-release');

As statet in http://gruntjs.com/api/grunt.task#grunt.task.renametask it should be possible to rename tasks. As I understood correctly the plugin should  lookup its configuration using:

`grunt.template.process(grunt.config.getRaw(this.name'+'.options.tagName')` 
 instead of  using hardcoded plugin name
`grunt.template.process(grunt.config.getRaw('release.options.tagName')`

**Comment by drublic** [comment]
#35 landed and thus this is fixed. Sorry for the delay and thanks for reporting.
