### ISSUE TITLE
Why would it brake my numbering and bump at once to a 4-digit patch?

### ISSUE THREAD

**Issue by beshur** [geddski/grunt-release#92]
Hi.

I had my versions managed with `grunt-tagrelease` like `0.2.6`.
Then grunt start saying it will depreceate soon, so after the first run `grunt-release` makes the version `0.2.1001`.
Why is that?

**Comment by drublic** [comment]
Thanks for reporting.
Is this a package.json file you are updating?
I've never come across such an issue myself. Please provide some more information about what you configured and what you do.

**Comment by beshur** [comment]
@drublic, yes, I'm updating package.json.
Config is like this:
```
grunt.initConfig({
	pkg: grunt.file.readJSON('package.json'),
	bumpup: {
		options: {
			updateProps: {
				pkg: 'package.json'
			}
		},
		file: 'package.json'
	},
	tagrelease: '<%= pkg.version %>'
});
```

**Comment by drublic** [comment]
Thanks for providing this feedback. It would be interesting what `release` does. Or do you use `bumpup` as an alias?

**Comment by beshur** [comment]
Actually did not get the question, @drublic.
But the other part of the gruntfile is like this:
```
// Alias task for release
grunt.registerTask('makeRelease', function (type) {
	type = type ? type : 'patch';     // Default release type
	grunt.task.run('bumpup:' + type); // Bump up the version
	grunt.task.run('tagrelease');     // Commit & tag the release
});
```

**Comment by drublic** [comment]
Can you please try to use the name `release` instead of `bumpup`? I currently don't have a solution for your problem. Sorry.

**Comment by drublic** [comment]
Thanks, @beshur! Closing this now. Please let me know if the problem occurs again.
