### ISSUE TITLE
Bump additional version number in separate package.json, for firefox addon

### ISSUE THREAD

**Issue by bobbyrne01** [geddski/grunt-release#95]
I have a firefox addon, which requires it's own `package.json`. I'd like the have `grunt-release` update both `package.json` files. But I'm getting a warning, which stops execution, when I set an `additionalFiles` value in my `Gruntfile.js`.

Any ideas why?

The directory structure of my project is as follows ..

    rob@work:~/git/repo$ tree
    .
    ├── addon
    │   └── package.json
    ├── Gruntfile.json
    └── package.json

Console output ..

    rob@work:~/git/repo$ grunt release --no-write
    Running "release" task
    Warning: Object addon/package.json has no method 'push' Use --force to continue.

    Aborted due to warnings.

Extract from `~/git/repo/Gruntfile.json` ..

    release: {
        options: {
            file: 'package.json',
            additionalFiles: 'addon/package.json',
            bump: true,
            add: true,
            commit: true,
            tag: true,
            push: true,
            pushTags: true,
            npm: false,
            npmtag: false,
            github: {
                repo: 'bobbyrne01/project',
                usernameVar: 'GITHUB_USERNAME',
                passwordVar: 'GITHUB_PASSWORD'
            }
        }
    },

Below is my `package.json` specific to the firefox addon (that lives at `~/git/repo/addon/package.json`).

It has the same `version` number as the `node` `package.json` residing at `~/git/repo/package.json` ..

    {
        "name": "repo",
        "title": "Repo",
        "id": "jid1-randomid",
        "description": "this is my description",
        "author": "bobbyrne01",
        "license": "GNU GPL v3",
        "version": "0.5.2"
    }

**Comment by drublic** [comment]
Thanks for reporting. Currently we only use an array as a possible input type for `additionalFiles`. We will change this.

In the meantime please use 

    additionalFiles: ['addon/package.json'],

in your configuration.

I hope this fixes the problem.

**Comment by bobbyrne01** [comment]
Perfect, thanks ..

    >> bumped version of addon/package.json to x.x.x
    >> bumped version of package.json to x.x.x

**Comment by drublic** [comment]
Fix this in the last commit. Please try master if you are interested. 
Again, thanks for reporting this bug and thus making grunt-release better :)
